#!/usr/bin/env python

import sys
import time
from datetime import datetime
from ttt import core

from strategies import simple, brazucaV2, brazucaV3Minimax, userInputStrategy
from strategies import bokito
from strategies import brazuca
from strategies import brazucaV1

Simple = core.Player("Simple", simple.strategy)
Bokito = core.Player("Bokito", bokito.strategy)
Brazuca = core.Player("Brazuca", brazuca.strategy)
BrazucaV1 = core.Player("BrazucaV1", brazucaV1.strategy)
BrazucaV2 = core.Player("BrazucaV2", brazucaV2.strategy)
BrazucaV3 = core.Player("BrazucaV3", brazucaV3Minimax.strategy)
UserInput = core.Player("UserInput", userInputStrategy.strategy)


# print core.play_double_game(size=3,one=Brazuca, two=UserInput)

# for i in range(1):
#     winner = core.play_game(size=4,one=Bokito, two=Brazuca)
#     print winner
#     if winner == "Bokito":
#         raise Exception("Bokito won! Something went wrong!!!")

start_time = datetime.now()
print core.play_match(size=3 , ndouble_games=100/2, one=Bokito, two=Brazuca)
time_elapsed = datetime.now() - start_time
print('Time elapsed (hh:mm:ss.ms) {}'.format(time_elapsed))